// Generated by CoffeeScript 1.8.0
(function() {
  var codeParsers, fs, parsers, utils, yaml, _;

  _ = require('underscore');

  fs = require('fs');

  fs.path = require('path');

  yaml = require('js-yaml');

  utils = require('./utils');

  codeParsers = {
    js: require,
    coffee: function(path) {
      require('coffee-script/register');
      return require(path);
    }
  };

  parsers = {
    json: JSON.parse,
    yml: yaml.safeLoad,
    yaml: yaml.safeLoad,
    txt: _.identity
  };

  exports.load = function(path, options) {
    var extension, fullPath, name, parse, raw, value;
    if (options == null) {
      options = {};
    }
    extension = fs.path.extname(path);
    if (options.type == null) {
      options.type = extension.slice(1);
    }
    fullPath = fs.path.resolve(path);
    name = (fs.path.basename(path)).slice(0, -extension.length);
    if (parse = codeParsers[options.type]) {
      try {
        value = parse(path);
      } catch (_error) {
        value = parse(fullPath);
      }
    } else {
      parse = parsers[options.type] || parsers.txt;
      raw = fs.readFileSync(fullPath, {
        encoding: 'utf8'
      });
      value = parse(raw);
    }
    if (options.namespace) {
      return utils.kv(name, value);
    } else {
      return value;
    }
  };

}).call(this);
